### PR TITLE
Fixes for capnp 1.0

### PR DESCRIPTION
**Pull request by ghost**
This PR is just a set of things I could fix so far. 

* Change type of read_min_bytes from size to int
* Adapt python_requires to >=3.8
* Replace deprecated find_module with find_spec (importlib)

### CODE REVIEW

**Comment by ghost** [comment]
Locally, everything works just fine (linux and mac) ... somehow the CI is having problems and reports the following error:

```AttributeError: '_UnixSelectorEventLoop' object has no attribute 'call_soon'```


But not every time and not in all builds 🙄

**Comment by ghost** [comment]
The last run seems to be pretty successful 
https://github.com/tobiasah/pycapnp/actions/runs/6404555479

**Comment by LasseBlaauwbroek** [comment]
> AttributeError: '_UnixSelectorEventLoop' object has no attribute 'call_soon'

As far as I remember, this happens when the `async` loop is closed, but you still try to schedule some stuff on it. If that is indeed happening, that would be a bug. Can you still reproduce? If so, do you have a log somewhere?

**Comment by ghost** [comment]
> > AttributeError: '_UnixSelectorEventLoop' object has no attribute 'call_soon'
> 
> As far as I remember, this happens when the `async` loop is closed, but you still try to schedule some stuff on it. If that is indeed happening, that would be a bug. Can you still reproduce? If so, do you have a log somewhere?

It happened in ci a few times when I fixed a couple of other things (e.g. https://github.com/tobiasah/pycapnp/actions/runs/6404330826/job/17384670123)  ... I could never reproduce it locally.  But it with the current version it never happened again (not even in ci) ... I tested/used the beta a lot in the last days, and it never occurred once 🙈

**Review by haata — APPROVED** [review]

**Comment by haata** [comment]
@tobiasah @LasseBlaauwbroek 
like this one? https://github.com/capnproto/pycapnp/actions/runs/6487790178/job/17618856042

**Comment by LasseBlaauwbroek** [comment]
This is a mystifying bug. I would have expected it to occur on some stress test that I wrote. Instead, it happens on very mundane code... I really don't know what causes it.
Obvervations:
- I ran the github CI a bunch of times. It seems to happen nondeterministically, around 1 in 10 runs: https://github.com/LasseBlaauwbroek/pycapnp/commits/test-bug-in-ci
  + It is consistently the tests in test_rpc_calculator.py. If one of the tests fails, they both fail.
  + It seems to happen across Linux, Mac and Windows
  + Occurs at least on py3.8 an py3.9
- I cannot locally reproduce it on my Linux laptop, even after 1000 runs of the test.

I'm now seeing if I can reduce the test where the failure occurs. But this will take a while, because every change has to be run in the CI a bunch of times. If someone else is able to reproduce, let me know.

**Comment by haata** [comment]
Hmm, I wonder if there's some odd behaviour with import gc. But to be honest I don't think that's the problem here as the gc test is the 2nd test (and pytest runs tests sequentially).

What might be happening here is that something odd is happening with the "re-import" of import async_calculator_client/async_calculator_server. This problem smells like a "slow filesystem" problem where something wasn't cleaned up fast enough and we're not seeing the actual error.
It would be really interesting to see if running pytest again on the same instance (maybe after sleeping a few seconds) to see if that helps.

**Comment by LasseBlaauwbroek** [comment]
I thought that too. But I believe I can exclude that hypothesis. Here is a version of the failing test where all of the code is inlined into a single file: https://github.com/LasseBlaauwbroek/pycapnp/actions/runs/6498256827/job/17649195912

**Comment by LasseBlaauwbroek** [comment]
For the record: I've now managed to reproduce this locally. It only seems to manifest on Python 3.8 and 3.9.

**Comment by haata** [comment]
> For the record: I've now managed to reproduce this locally. It only seems to manifest on Python 3.8 and 3.9.

Yeah, that matches from what I've seen. In the worst worst case we can exclude these tests from Python 3.8 and 3.9.
My suspicion is that there were asyncio changes in 3.10 (that probably made things better?).

I've seen questions like this https://stackoverflow.com/questions/73599594/asyncio-works-in-python-3-10-but-not-in-python-3-8 in the wild.

**Pull request merged**
